### ISSUE TITLE
Clean up pull request for `new-api`

### ISSUE THREAD

**Issue by nidhal-labidi** [compose-us/flottform#23]
**Description** 

There is a larger PR open to change the API for Flottform to allow easier changes to the UI. We want to merge this idea, fix open issues with the API and then optimize it.

**Links / References**

- See PR #22 

**Tasks / Definition of Done**

- [ ] Remove prototype API files
- [ ] Merge `new-api` PR
- [ ] Add tasks for open issues after the merge

**Further information**

After prototyping on Flottform and making sure the idea works for different use-cases, we need to clean up and find a good API for developers to use.
