### ISSUE TITLE
Add option to set a label for the input field inside the popup

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#25]
**Description** 

Developers should be able to add labels for each input field. Flottform should show this label in the default UI or allow to reference it somehow.

**Links / References**

\-

**Tasks / Definition of Done**

- [x] Add option to change the "Connect your devices" label / title. Default should be "Fill from Another Device"
- [x] Add a description field to the UI that can be changed. Default to "This form is powered by Flottform. Need to add details from another device? Simply click a button below to generate a QR code or link, and easily upload information from your other device."
- [x] Add label to input field section in the "Connect your devices" UI. Default label for input field should be its `id` attribute or `name` if `id` doesn't exist or `""` if nothing is set. Developers may put an `""` as default themselves though!
- [x] Add option to override the label of the button
- [x] Test it on a demo form

**Further information**

The current UI in the `new-api` PR only shows "Get link" as it does not have the label or an ID available.
