### ISSUE TITLE
Review API for customizing styles

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#29]
**Description** 

With the new API, we separated the UI parts and added a new default UI. We want to review how it's possible to customize it by changing simple parts or overriding the default UI with a completely custom one.

**Links / References**

\-

**Tasks / Definition of Done**

- [x] Create a new example with three input fields
  - [x] First one uses the default UI without any customisation (See in #45)
  - [x] Second one uses the default UI (See in #43)
  - [x] Third one uses a completely custom UI (embedded into the form as we had in the current prototype / screencast) (See in #40)
  - [x] The default UI should have some values changed (like colors of progress bar) through CSS variables / custom stylesheet (See in #43)

**Further information**

We don't think anybody would want to customize the styles of single items of the default UI as it would make it look inconsistent.
