### ISSUE TITLE
Update mobile layout for default UI

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#38]
**Description** 

We need to update mobile layout so it would work smoothly on different devices

**Links / References**

\

**Tasks / Definition of Done**

- [ ] Move Flottform container to the side on smaller screens
- [ ] Change open button text to 📱 icon on mobile
- [ ] Test it on different screen sizes

**Further information**

\

**Comment by TamaraBogantseva** [comment]
We decided to let user pass an anchor element for Flottform root container, so he would have more flexibility not only with mobile layout but also with positioning. Therefore this issue is outdated and we won't plan to do it
