### ISSUE TITLE
Test how easy it is to implement Flottform with a custom UI

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#40]
**Description** 

We want to check if it's easy to use Flottform and implement it in a simple form

**Links / References**

Further links on the topic

**Tasks / Definition of Done**

- [ ] Create simple form
- [ ] Use custom button to call Flottform for one input field
- [ ] Add a link and qr code in our form

**Further information**

It can look like on our first demo 😄
