### ISSUE TITLE
Test how defaultUI works on different forms

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#43]
**Description** 

We want to test if default UI would work great with different forms (styles, colors, layout) and how easy to customise it

**Links / References**

\

**Tasks / Definition of Done**

- [ ] Create new simple form with different layout and color theme that we have on our demos
- [ ] Use Flottform with defaultUI there
- [ ] See how easy it is to implement it
- [ ] If there are any issues - document them and update default UI 

**Further information**

\
