### ISSUE TITLE
Implement new default UI on demo page

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#45]
**Description** 

Since we changed default UI, we need to implement it on a demo page. We may also want to have several pages with different UIs that we already have

**Links / References**

\

**Tasks / Definition of Done**

- [x] Update demo page with new default UI
- [x] Deploy new page
- [x] Create a new issue for blog post about it

**Further information**

\

**Comment by TamaraBogantseva** [comment]
We have deployed everything already
