### ISSUE TITLE
Research what do we need to create a browser extension for Flottform

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#47]
**Description** 

We need to consider a lot of stuff before we can publish a browser extension, such as security questions, payment systems and UI

**Links / References**

\

**Tasks / Definition of Done**

- [ ] Find out about needed security measures 
- [ ] Find out about payment systems and their compatibility with a german law
- [ ] Research how such browser extension should be build
- [ ] Create new issues for that

**Further information**

\
