### ISSUE TITLE
Make all strings we have in a default component configurable

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#52]
**Description** 

All texts / labels need to be configurable in order to give more flexibility for developers who wants to use default theme

**Links / References**

[Comment 1](https://github.com/compose-us/flottform/pull/39#discussion_r1756612739)
[Comment 2](https://github.com/compose-us/flottform/pull/39#discussion_r1756611923)
[Comment 3](https://github.com/compose-us/flottform/pull/39#discussion_r1756610416)

**Tasks / Definition of Done**

- [ ] Make all texts configurable
- [ ] Use correct types
- [ ] Move the default texts into an object

**Further information**

\-
