### ISSUE TITLE
Create API docs for published APIs

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#53]
**Description** 

We expose a few functions and types. All of this should be documented. If we document this with JSDoc, we should be able to generate nice API docs

**Links / References**

- Search for JSDocs and generators

**Tasks / Definition of Done**

- [ ] Document all exposed APIs
- [ ] Generate HTML from the JSDoc
- [ ] Link to the generated HTML or allow it to be browsed from the GitHub repo or (preferably) from flottform.io

**Further information**

On the developer page, outlining the general usage and examples, this should be linked as well.

**Comment by TamaraBogantseva** [comment]
We will have another issue for improving the docs, but we need to publish this one in order to have some documentation
