### ISSUE TITLE
Move where-are-you.at into new repository

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#57]
**Description** 

While where-are-you.at is a nice demo of Flottform's capabilities, we should move it out of the official repo into another example repository. We have created it during a Hackathon and it was only used there to benefit from the existing deployment process.

It should have a dedicated deployment and repository.

**Links / References**

- See flottform/where-are-you-at

**Tasks / Definition of Done**

- [ ] Create new (public) repository for where-are-you.at
- [ ] Move package into that repository
- [ ] Use the official `@flottform` packages

**Further information**

We need to publish official `@flottform` packages to be able to do this first
