### ISSUE TITLE
Fix linter issues

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#59]
**Description** 

We started without actually having linter and tests in our CI. When looking into the linter scripts, we could see that there are quite a few things to fix or warnings to check.

**Links / References**

- `pnpm run -r format` for formatting
- `pnpm run -r lint` for linting

**Tasks / Definition of Done**

- [x] Update all packages to eslint 9
- [x] Ensure linting works in all packages
- [ ] Fix linter warnings

**Further information**

This should be an automated check in the future for every pull request.
