### ISSUE TITLE
Add linter check for pull requests

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#60]
**Description** 

There are no automated checks before merging a pull request yet. We should at least include format and lint checks.

**Links / References**

- See GitHub actions

**Tasks / Definition of Done**

- [ ] Create GitHub action workflow file for pull requests
- [ ] Ensure all packages are running format check
- [ ] Ensure all packages are running linter check
- [ ] Ensure all packages are running tests

**Further information**

We may need to check the tests as well. They seem to not be in a usable state right now.

**Comment by TamaraBogantseva** [comment]
I've started to do it, see branch https://github.com/compose-us/flottform/tree/add-linter-check

**Comment by Narigo** [comment]
I think running `pnpm -r run lint` should already work, without needing to do the `matrix` and running the linter individually.
