### ISSUE TITLE
Allow setting a TURN server through an environment variable

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#68]
**Description** 

For our current demos, we don't use a TURN server yet. We should have one so that the demo works in all the cases wherever we present Flottform.

**Links / References**

- https://webrtc.org/getting-started/turn-server

**Tasks / Definition of Done**

- [ ] Create environment variable for authentication key for enabling / disabling credential fetch
- [ ] Create environment variables for TURN server url and credentials
- [ ] Create a `PUT` route on the server to enable or disable retrieval of TURN server credentials (with some predefined authentication key set through an environment variable)
  - [ ] Create a route that does the `PUT` request when providing our credentials in an input field + a checkbox whether to enable or disable the TURN credentials
- [ ] Allow client to check for TURN server credentials (if nothing comes back, it does nothing, if it receives a configuration, it uses it for the `iceServers` configuration option in `RTCPeerConnection`)

**Further information**

This should be a good first step before we implement this on an API key basis by users.
