### ISSUE TITLE
Update repo subfolders to have a better structure

### ISSUE THREAD

**Issue by TamaraBogantseva** [compose-us/flottform#85]
**Description** 

The repository structure needs to be updated to improve organization and make it easier to navigate. Specifically:
- Consolidate all Flottform library modules into a `core` folder for better grouping and clarity.
- Use a `demo` folder to house demo-related files and components.
- Move the `where-are-you-at` to a separate repository.
These changes will help streamline the repository, separating concerns and making the purpose of each part more apparent.

**Links / References**

\-

**Tasks / Definition of Done**

- [x] Move all Flottform library modules into a `core` subfolder.
- [ ] Extract the `where-are-you-at` into a new repository. #57 
- [x] Update any file paths, imports, or references affected by these changes.

**Further information**

This restructuring will make the repository more intuitive for contributors and users by logically organizing files and separating unrelated components into their own repository.

**Comment by Narigo** [comment]
We'll keep the `flottform` for `forms` and `server` packages and added a `servers` folder for the other parts.

where-are-you.at and Traefik etc would need to be somewhere else. We should move the `web` network to `external: true` and allow it to run on the same server as `demo.flottform.io` OR use the published packages.
