### ISSUE TITLE
Update to Svelte 5

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#90]
**Description** 

Svelte 5 was released a few weeks ago. We should update all modules to use the latest version.

**Links / References**

- [Migration guide](https://svelte.dev/docs/svelte/v5-migration-guide)

**Tasks / Definition of Done**

- [ ] Update all packages to Svelte 5
- [ ] Do necessary changes
- [ ] Check that everything still works

**Further information**

\-
