### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Narigo** [compose-us/flottform#91]
**Description** 

We need to set a license in order to publish and distribute Flottform packages, browser extensions, etc.

**Links / References**

- See the CUNCL document

**Tasks / Definition of Done**

- [ ] Publish the CUNCL document
- [ ] Add CUNCL to the project as LICENSE.md
- [ ] Refer to CUNCL 

**Further information**

\-
