### ISSUE TITLE
Implement a Class for Managing Input Connections

### ISSUE THREAD

**Issue by nidhal-labidi** [compose-us/flottform#98]
**Description** 

We need to create a class that encapsulates the logic for managing input field connections on the page context. 

The class should track open connections and close all of them when we have to.

**Links / References**

/-

**Tasks / Definition of Done**

- [x] Create the class "ConnectionManager".
- [x] Add it to the module forms.
- [x] Use it inside the page context of the extension.

**Further information**

/-
